# Generated by Django 5.1.1 on 2025-06-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='frame_image',
            field=models.ImageField(blank=True, null=True, upload_to='alert_frames/', verbose_name='Captured Frame'),
        ),
        migrations.AddField(
            model_name='alert',
            name='frame_url',
            field=models.URLField(blank=True, null=True, verbose_name='Frame URL'),
        ),
    ]
