# Generated by Django 5.1.1 on 2025-06-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_alert_frame_image_alert_frame_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workerId', models.CharField(max_length=20, unique=True, verbose_name='Worker ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('department', models.CharField(max_length=100, verbose_name='Department')),
                ('supervisor', models.CharField(max_length=100, verbose_name='Supervisor')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('hire_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Worker',
                'verbose_name_plural': 'Workers',
                'ordering': ['name'],
            },
        ),
    ]
