# Generated by Django 5.1.1 on 2025-06-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker', models.CharField(max_length=100)),
                ('workerId', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('supervisor', models.CharField(max_length=100)),
                ('event', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('camera_id', models.IntegerField()),
                ('alert_type', models.CharField(max_length=50)),
                ('alert_id', models.IntegerField(blank=True, null=True)),
                ('frame_image', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
