# Generated by Django 5.1.1 on 2025-06-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='department',
        ),
        migrations.AddField(
            model_name='report',
            name='worker_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
