# Generated by Django 5.2.1 on 2025-11-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_remove_report_department_report_worker_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('no_helmet', 'No Helmet'), ('fire', 'Fire'), ('danger_zone', 'Danger Zone'), ('fall', 'Fall'), ('pre_fall', 'Pre-Fall')], max_length=50),
        ),
    ]
