# Generated by Django 5.2.1 on 2025-11-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_alter_alert_alert_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('no_helmet', 'No Helmet'), ('fire', 'Fire'), ('danger_zone', 'Danger Zone'), ('fall', 'Fall')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='alert',
            name='camera_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='worker_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='alert_type',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='camera_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='worker',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='workerId',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['-timestamp', 'camera_id'], name='monitor_ale_timesta_450a70_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['camera_id', '-timestamp'], name='monitor_ale_camera__acc096_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_type', '-timestamp'], name='monitor_ale_alert_t_3bcbbf_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['-timestamp'], name='monitor_rep_timesta_e403f3_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['workerId', '-timestamp'], name='monitor_rep_workerI_af615c_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['camera_id', '-timestamp'], name='monitor_rep_camera__e377d5_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['alert_type', '-timestamp'], name='monitor_rep_alert_t_fcd934_idx'),
        ),
    ]
