# Generated by Django 5.2.1 on 2025-11-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_alter_alert_options_alter_report_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='alert',
            name='monitor_ale_timesta_450a70_idx',
        ),
        migrations.RemoveIndex(
            model_name='alert',
            name='monitor_ale_camera__acc096_idx',
        ),
        migrations.RemoveIndex(
            model_name='alert',
            name='monitor_ale_alert_t_3bcbbf_idx',
        ),
        migrations.RemoveIndex(
            model_name='report',
            name='monitor_rep_timesta_e403f3_idx',
        ),
        migrations.RemoveIndex(
            model_name='report',
            name='monitor_rep_workerI_af615c_idx',
        ),
        migrations.RemoveIndex(
            model_name='report',
            name='monitor_rep_camera__e377d5_idx',
        ),
        migrations.RemoveIndex(
            model_name='report',
            name='monitor_rep_alert_t_fcd934_idx',
        ),
        migrations.AddField(
            model_name='camera',
            name='viewing_angle',
            field=models.CharField(choices=[('frontal', 'Frontal (Eye Level)'), ('top_down', 'Top-Down (CCTV)'), ('angled', 'Angled (45°)')], default='frontal', help_text='Camera mounting angle - affects fall detection thresholds', max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('no_helmet', 'No Helmet'), ('fire', 'Fire'), ('danger_zone', 'Danger Zone'), ('fall', 'Fall')], max_length=50),
        ),
        migrations.AlterField(
            model_name='alert',
            name='camera_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='alert',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='worker_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='alert_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='camera_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='worker',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='workerId',
            field=models.CharField(max_length=50),
        ),
    ]
